### ISSUE TITLE
what is the headers when pushing your reviews to the content pool using a webhook？

### ISSUE THREAD

**Issue by niceyida** [LLMine/llmine_core#23]
when I push data to the content pool using a webhook with no headers ,it response as follows：
```
{
	"detail": "Authentication credentials were not provided."
}
```

**Comment by arpanpreneur** [comment]
Hi @niceyida we will soon release the full documentation. But for now, you can see a `schema.yml` file in main branch. Please paste its content in https://editor.swagger.io/ to get a working documentation of the REST API and webhooks.

To answer your question, if you are calling the webhook from another server, just generate an API-Key first using the admin panel (you will see a link in the sidebar). Then use put an `Authorization` header like
`Api-Key <YOUR KEY>`

Also, the correct request body would be
```
{
  "text_content": "Your content.",
  "metadata_json": {}
}
```

Correct URL: `POST` to `{{host}}/api/v1/push-content/{{content-pool-name}}/{{datasource-name}}/`

**Comment by niceyida** [comment]
Hi @arpanpreneur It works,thanks for your reply. But I meet another issue, when I put Ingested Text Data successfully, the Processed datas is empty.Before, I had set chain and propmt. Can you give me some solution suggestions?
![Snipaste_2023-09-26_17-05-31](https://github.com/LLMine/llmine_core/assets/18515552/8bf79bd9-da93-4f64-a927-fbcb184079c9)
![Snipaste_2023-09-26_17-11-06](https://github.com/LLMine/llmine_core/assets/18515552/90a92555-2c36-4ec7-8398-58cc823abc4e)
![Snipaste_2023-09-26_17-11-23](https://github.com/LLMine/llmine_core/assets/18515552/db2b6667-e708-4757-9205-c4fcb797fe63)
![Snipaste_2023-09-26_17-11-36](https://github.com/LLMine/llmine_core/assets/18515552/8a91c1d1-4276-496e-af09-80737e8695fe)
![Snipaste_2023-09-26_17-11-49](https://github.com/LLMine/llmine_core/assets/18515552/5d708479-f516-4b03-afb2-3fd6678e3132)

**Comment by arpanpreneur** [comment]
Hi, here are a few things you can check

1. OpenAI Key is valid in env file and loaded properly (check the value of `echo $OPENAI_API_KEY` in the terminal you are doing `runserver` and also in the terminal you are starting the celery process)
2. You can make requests to OpenAI using the account you generated the Key from (just use the playground to verifiy)
3. You have started the celery process in the way mentioned in the README.
4. See if you notice any exception / failure in the celery process.

Please let me know if this helps you debug this.

**Comment by arpanpreneur** [comment]
@niceyida Is there an update on this ticket? Please let me know if you have solved it already, in that case, we will close the issue.

**Comment by niceyida** [comment]
@arpanpreneur I confirmed that I have run celery and no errors were reported, but process_data is still empty. In addition, I also confirmed that my openai_key is valid. I don't know where to check now.

**Comment by arpanpreneur** [comment]
Let us connect and check this over a quick call. Connect me on LinkedIn or X with the handle @arpanpreneur in both places. @niceyida 

https://www.linkedin.com/in/arpanpreneur/

**Comment by niceyida** [comment]
Hi, @arpanpreneur.Maybe this issue can be closed first, and I can wait until the official version of the detailed documentation is released before testing. Thank you for your patient answer here.

**Comment by arpanpreneur** [comment]
Sure, let me know if we have a way to connect. I would love to understand potential use cases you are trying, that would help us give more informed direction we could take this project towards.

Closing this issue.
